# Generated by Django 3.1.6 on 2021-04-03 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashbird', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='bird_photo',
            field=models.ImageField(default='media/default.jpg', upload_to=''),
        ),
    ]
